# Maven
# Build your Java project and run tests with Apache Maven.
# Add steps that analyze code, save build artifacts, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/java

trigger:
- main

pool:
  vmImage: ubuntu-latest

steps:
- task: JavaToolInstaller@0
  inputs:
    versionSpec: '11'
    jdkArchitectureOption: 'x64'

- task: Maven@3
  inputs:
    mavenPomFile: './maveproject1/pom.xml'
    publishJUnitResults: true
    testResultsFiles: '**/surefire-reports/TEST-*.xml'
    javaHomeOption: 'JDKVersion'
    jdkVersionOption: '11'
    mavenVersionOption: 'Default'
    mavenOptions: '-Xmx3072m'
    mavenAuthenticateFeed: false
    effectivePomSkip: false
    goals: 'clean install'

- task: SonarQubePrepare@6
  inputs:
    SonarQube: 'My_SonarQube'
    scannerMode: 'CLI'
    configMode: 'file'
    configFile: 'sonar-project.properties'

- task: Maven@3
  inputs:
    mavenPomFile: './mavenproject1/pom.xml'
    goals: 'sonar:sonar'
    options: '-Dsonar.projectKey=your_project_key -Dsonar.host.url=$(SONARQUBE_URL) -Dsonar.login=$(SONARQUBE_TOKEN)'

- task: SonarQubeAnalyze@6

- task: SonarQubePublish@6
  inputs:
    pollingTimeoutSec: '300'
